Repository OpenSID/OpenDK, pull requests merged in 2022-05, with the labels that each got.

#403 Susulan : Sesuaikan sebutan desa yang tidak muncul
  app/Models/DataDesa.php
  catatan_rilis.md
  database/migrations/2022_05_15_121032_default_sebutan_desa.php
  resources/views/layouts/frontends/footer.blade.php
  resources/views/layouts/frontends/header.blade.php
Labels: Teknis

#380 Sinkronisasi Data Pembangunan OpenSID ke OpenDK
  app/Http/Controllers/Api/PembangunanController.php
  app/Http/Controllers/Data/DataPembangunanController.php
  app/Http/Requests/PembangunanDokumentasiRequest.php
  app/Http/Requests/PembangunanRequest.php
  app/Imports/SinkronPembangunan.php
  app/Imports/SinkronPembangunanDokumentasi.php
  app/Models/Pembangunan.php
  app/Models/PembangunanDokumentasi.php
  catatan_rilis.md
  database/migrations/2022_04_17_225617_create_table_das_pembangunan.php
  database/migrations/2022_04_18_070823_create_table_das_pembangunan_dokumentasi.php
  resources/views/data/pembangunan/index.blade.php
  resources/views/data/pembangunan/rincian.blade.php
  resources/views/layouts/fragments/sidebar.blade.php
  routes/api.php
  routes/web.php
Labels: fitur

#404 perbaiki edit slider
  catatan_rilis.md
  resources/views/setting/slide/edit.blade.php
  resources/views/setting/slide/form.blade.php
Labels: bug

#392 perbaikan upload gagal pada update user dan perbaikan error message
  .gitignore
  app/Http/Controllers/User/UserController.php
  app/Models/User.php
  catatan_rilis.md
  helpers/general_helper.php
  public/uploads/user/2.jpg
  public/uploads/user/3.jpg
  public/uploads/user/4.jpg
  public/uploads/user/user1-128x128.jpg
  public/uploads/user/user3-128x128.jpg
  resources/views/layouts/fragments/header.blade.php
  resources/views/user/edit.blade.php
  resources/views/user/form.blade.php
Labels: bug

#411 Artikel desa yang baru tidak tampil
  app/Http/Controllers/Page/PageController.php
  catatan_rilis.md
  resources/views/pages/berita/feeds.blade.php
Labels: bug

#410 Fitur Impor Program Bantuan
  app/Http/Controllers/Data/ProgramBantuanController.php
  catatan_rilis.md
  resources/views/data/program_bantuan/import.blade.php
  resources/views/data/program_bantuan/index.blade.php
  resources/views/data/program_bantuan/show.blade.php
  storage/app/public/template_upload/program_bantuan.zip
Labels: fitur

#418 pr - Susulan sinkronisasi
  app/Http/Controllers/Api/PembangunanController.php
  app/Http/Requests/PembangunanDokumentasiRequest.php
Labels: Teknis

#419 perbaiki peta tidak tampil
  resources/views/data/data_desa/peta.blade.php
Labels: bug

#422 Susulan : sinkronsisai bantuan dan sinkronisasi program
  app/Http/Controllers/Api/PembangunanController.php
  app/Http/Controllers/Data/DataPembangunanController.php
  app/Http/Controllers/Data/ProgramBantuanController.php
  resources/views/data/program_bantuan/show.blade.php
  routes/web.php
Labels: bug, Teknis

#423 pr susulan : peta wilayah
  resources/views/data/data_umum/edit.blade.php
  resources/views/data/data_umum/form_edit.blade.php
Labels: Teknis
