Repository OpenSID/OpenDK, pull requests merged in 2022-04, with the labels that each got.

#363 Sikronisasi data Penduduk OpenSID ke OpenDK
  app/Http/Controllers/Api/PendudukController.php
  app/Http/Controllers/DashboardController.php
  app/Imports/SinkronPenduduk.php
  catatan_rilis.md
  config/app.php
Labels: bug

#373 Scrollbar Pada Menu List Nama Desa
  public/css/custom.css
  resources/views/layouts/frontends/header.blade.php
Labels: fitur

#367 perbaikan issue #354
  resources/views/data/penduduk/form_show.blade.php
  resources/views/data/penduduk/form_show_status_kehamilan.blade.php
  resources/views/data/penduduk/index.blade.php
  resources/views/data/penduduk/show.blade.php
Labels: kontributor

#371 Solusi tipologi issue
  app/Http/Controllers/Data/DataUmumController.php
  database/migrations/2022_04_12_194536_alter_table_das_data_umum_modify_tipologi.php
  resources/views/data/data_umum/edit.blade.php
  resources/views/data/data_umum/form_edit.blade.php
Labels: kontributor

#374 Sesuaikan Format Angka
  app/Http/Controllers/Page/AnggaranRealisasiController.php
  app/Http/Controllers/Page/KependudukanController.php
  catatan_rilis.md
  helpers/general_helper.php
  resources/views/pages/anggaran_desa/detail_anggaran.blade.php
  resources/views/pages/anggaran_desa/show_anggaran_desa.blade.php
  resources/views/pages/anggaran_realisasi/show_anggaran_realisasi.blade.php
  resources/views/pages/kependudukan/show_kependudukan.blade.php
  resources/views/pages/kesehatan/show_kesehatan.blade.php
  resources/views/pages/pendidikan/show_pendidikan.blade.php
  resources/views/pages/program_bantuan/show_program_bantuan.blade.php
  resources/views/partials/asset_numeraljs.blade.php
Labels: fitur

#379 Ambil data tingkat pendidikan dari data hasil sinkronisasi penduduk di opensid
  app/Imports/SinkronPenduduk.php
  catatan_rilis.md
  database/migrations/2022_04_17_203223_import_log_nullable.php
Labels: fitur

#362 error migrasi 2022_03_09_134418_create_permission_tables.php
  catatan_rilis.md
  database/migrations/2022_03_09_134418_create_permission_tables.php
  database/migrations/2022_03_13_103220_add_remember_user.php
Labels: bug

#372 das_setting' doesn't exist
  app/Providers/AppServiceProvider.php
  catatan_rilis.md
Labels: bug

#375 Sediakan group pengguna kontributor berita
  app/Http/Controllers/Auth/LoginController.php
  catatan_rilis.md
  database/migrations/2022_04_24_144702_role_kontributor_artikel.php
  resources/views/layouts/fragments/sidebar.blade.php
Labels: fitur

#378 tambahkan sinkronisasi identitas desa
  app/Http/Controllers/Api/ProfilDesaController.php
  app/Http/Requests/ProfilDesaRequest.php
  catatan_rilis.md
  database/migrations/2022_04_17_002342_tambah_kolom_desa.php
  resources/views/layouts/frontends/footer.blade.php
  resources/views/layouts/frontends/header.blade.php
  routes/api.php
Labels: fitur

#386 Perbaharui link demo OpenDK
  README.md
  catatan_rilis.md
Labels: bug

#396 perbaikan menu desa yang terpotong
  public/css/custom.css
Labels: bug

#398 tambahkan jquery validation
  catatan_rilis.md
  resources/views/partials/asset_jqueryvalidation.blade.php
  resources/views/user/form.blade.php
Labels: Teknis

#394 perbaiki form upload file hilang setelah gagal upload
  catatan_rilis.md
  resources/views/informasi/event/form_create.blade.php
  resources/views/informasi/event/form_edit.blade.php
Labels: bug

#397 perbaiki penamaan class karena di linux tidak terbaca
  app/Models/DataDesa.php
  catatan_rilis.md
  resources/views/informasi/event/form_create.blade.php
  resources/views/informasi/event/form_edit.blade.php
  resources/views/partials/asset_jqueryvalidation.blade.php
  resources/views/user/form.blade.php
Labels: Teknis
