Repository OpenSID/OpenDK, pull requests merged in 2022-11, with the labels that each got.

#524 Perbaiki relasi pembangunan
  app/Models/DataDesa.php
  app/Models/Pembangunan.php
  app/Models/PembangunanDokumentasi.php
  catatan_rilis.md
Labels: Teknis

#526 Perbaiki relasi potensi
  app/Models/Potensi.php
  app/Models/TipePotensi.php
  catatan_rilis.md
Labels: Teknis

#530 Perbaiki foto penduduk
  app/Models/Komplain.php
  catatan_rilis.md
  resources/views/sistem_komplain/komplain/index.blade.php
  resources/views/sistem_komplain/komplain/show.blade.php
Labels: bug

#527 Jabatan
  app/Enums/JenisJabatan.php
  app/Http/Controllers/Data/JabatanController.php
  app/Http/Requests/JabatanRequest.php
  app/Models/Jabatan.php
  catatan_rilis.md
  composer.json
  database/migrations/2022_11_06_191838_create_ref_jabatan_table.php
  resources/views/data/jabatan/create.blade.php
  resources/views/data/jabatan/edit.blade.php
  resources/views/data/jabatan/form.blade.php
  resources/views/data/jabatan/index.blade.php
  resources/views/layouts/fragments/error_message.blade.php
  resources/views/layouts/fragments/sidebar.blade.php
  routes/web.php
Labels: fitur

#531 Perangkat kecamatan
  catatan_rilis.md
  resources/views/data/pengurus/form.blade.php
Labels: fitur

#550 Susulan pengurus
  app/Http/Controllers/Data/PengurusController.php
  app/Http/Controllers/User/UserController.php
  app/Http/Requests/UserRequest.php
  app/Http/Requests/UserUpdateRequest.php
  app/Models/Pengurus.php
  catatan_rilis.md
  resources/views/data/pengurus/index.blade.php
Labels: fitur, susulan

#536 Perbaiki foto artikel tidak terhapus
  app/Http/Controllers/Data/AdminKomplainController.php
  app/Http/Controllers/Informasi/ArtikelController.php
  catatan_rilis.md
Labels: bug

#537 Tambahkan data untuk di kirim ke tracksid
  app/Http/Controllers/Controller.php
Labels: Teknis

#564 Perbaiki foto sinergi tidak tampil dihalaman lain selain halaman utama
  catatan_rilis.md
  resources/views/widgets/sinergi_program.blade.php
Labels: bug

#566 Perbaiki foto media sosial tidak muncul di halaman lain
  catatan_rilis.md
  resources/views/widgets/media_sosial.blade.php
Labels: bug

#568 Perbaiki edit grup pengguna selalu admin desa
  catatan_rilis.md
  resources/views/user/form.blade.php
Labels: bug

#569 Perbaiki kolom id kartu peserta
  catatan_rilis.md
  database/migrations/2022_11_24_181234_update_id_kartu_program_bantuan.php
Labels: bug

#563 Refactor sidebar admin
  app/Http/Controllers/Controller.php
  catatan_rilis.md
  resources/views/layouts/fragments/sidebar.blade.php
Labels: Teknis
