Repository OpenSID/OpenDK, pull requests merged in 2022-08, with the labels that each got.

#318 Laravel v7.x
  app/Exceptions/Handler.php
  composer.json
  config/app.php
  config/cache.php
  config/filesystems.php
  config/mail.php
  config/queue.php
  config/session.php
Labels: Teknis, kontributor

#409 Terapkan sentry untuk menangkap log
  .env.example
  app/Exceptions/Handler.php
  composer.json
  config/sentry.php
Labels: fitur

#451 Tombol jalankan queue listener
  app/Http/Controllers/LogViewerController.php
  public/img/loading.gif
  resources/views/vendor/laravel-log-viewer/kebutuhan-sistem.blade.php
  routes/web.php
Labels: fitur

#455 Media sosial widget
  app/Http/Controllers/Controller.php
  app/Http/Controllers/Informasi/MediaSosialController.php
  app/Models/MediaSosial.php
  catatan_rilis.md
  database/migrations/2022_07_14_102805_create_media_sosial_table.php
  resources/views/informasi/media_sosial/create.blade.php
  resources/views/informasi/media_sosial/edit.blade.php
  resources/views/informasi/media_sosial/form.blade.php
  resources/views/informasi/media_sosial/index.blade.php
  resources/views/informasi/media_sosial/navigasi.blade.php
  resources/views/layouts/fragments/sidebar.blade.php
  resources/views/layouts/frontends/sidebar.blade.php
  resources/views/widgets/media_sosial.blade.php
  routes/web.php
Labels: fitur

#465 Perbaiki sinkronisasi berita OpenSID ke OpenDK
  app/Models/DataDesa.php
  catatan_rilis.md
Labels: bug

#467 Perbaiki peta koordinat data umum kosong
  app/Imports/ImporPendudukKeluarga.php
  app/Models/DataDesa.php
  app/Models/DataUmum.php
  catatan_rilis.md
  resources/views/data/data_desa/peta.blade.php
  resources/views/partials/asset_leaflet.blade.php
  routes/api.php
  routes/web.php
Labels: bug

#469 Susulan medsos
  app/Http/Controllers/Informasi/MediaSosialController.php
  resources/views/informasi/media_sosial/form.blade.php
  resources/views/layouts/frontends/sidebar.blade.php
  resources/views/widgets/media_sosial.blade.php
Labels: fitur

#470 Susulan tombol queue
  app/Http/Controllers/LogViewerController.php
  public/img/loading.gif
  public/js/sweetalert2/sweetalert2.all.min.js
  public/js/sweetalert2/sweetalert2.min.css
  resources/views/partials/asset_sweetalert.blade.php
  resources/views/vendor/laravel-log-viewer/kebutuhan-sistem.blade.php
Labels: fitur

#468 463 sinergi program
  app/Http/Controllers/Controller.php
  app/Http/Controllers/Informasi/SinergiProgramController.php
  app/Models/SinergiProgram.php
  catatan_rilis.md
  database/migrations/2022_08_22_062136_create_sinergi_program_table.php
  resources/views/forms/aksi.blade.php
  resources/views/informasi/sinergi_program/create.blade.php
  resources/views/informasi/sinergi_program/edit.blade.php
  resources/views/informasi/sinergi_program/form.blade.php
  resources/views/informasi/sinergi_program/index.blade.php
  resources/views/informasi/sinergi_program/navigasi.blade.php
  resources/views/layouts/fragments/sidebar.blade.php
  resources/views/layouts/frontends/sidebar.blade.php
  resources/views/widgets/sinergi_program.blade.php
  routes/web.php
Labels: fitur

#472 Perbaiki penduduk tetap masuk ketika desa kosong
  app/Imports/SinkronPenduduk.php
  catatan_rilis.md
Labels: bug

#477 476 logo medsos
  catatan_rilis.md
  public/css/custom.css
  resources/views/widgets/media_sosial.blade.php
Labels: bug

#478 475 gambar sinergi program
  catatan_rilis.md
  public/css/custom.css
  resources/views/widgets/sinergi_program.blade.php
Labels: bug
